apiVersion: v1
kind: Service
metadata:
  name: smartgate-svc
spec:
  selector:
    app: smartgate-app
  ports:
    - port: 80
      name: http
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: smartgate-svc-api
spec:
  selector:
    app: smartgate-app
  ports:
    - port: 80
      name: http
      targetPort: 30147
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartgate-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartgate-app
  template:
    metadata:
      labels:
        app: smartgate-app
    spec:
      containers:
        - name: smartgate-app
          image: 'registry.c2atec.com/smartgate:1.7'
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-ingress-c2a
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: arruda.smartgate.c2atec.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smartgate-svc
                port:
                  number: 80
    - host: api-arruda.smartgate.c2atec.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smartgate-svc-api
                port:
                  number: 80
  ingressClassName: nginx
  tls:
    - hosts:
        - arruda.smartgate.c2atec.com
        - api-arruda.smartgate.c2atec.com
      secretName: tls-smartgate-ingress
